# Generated by Django 3.2.4 on 2021-06-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20210629_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizes',
            name='plan',
        ),
        migrations.AddField(
            model_name='sizes',
            name='plan',
            field=models.ManyToManyField(to='images.Plans'),
        ),
    ]
