# Generated by Django 3.2.4 on 2021-06-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_alter_storage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message/%Y/%m/%d/'),
        ),
    ]
