# Generated by Django 3.2.4 on 2021-06-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='file',
            field=models.ImageField(default=True, upload_to='media'),
        ),
    ]
